disabled_rules:
    - identifier_name
    - line_length
    
type_body_length:
    warning: 300
    error: 700
    
function_parameter_count:
    warning: 6
    error: 20
    
excluded: 
  - Pods
 
vertical_whitespace:
    max_empty_lines: 2