name: Actions

on:
  pull_request

jobs:
  Build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Start Xcode Build
      run: xcodebuild clean -project Facebook/Facebook.xcodeproj -scheme Facebook -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.0'
  
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --force-exclude
        env:
        WORKING_DIRECTORY: Facebook
