name: ActionsTest

on:
  pull_request

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Start Xcode Build
      run: xcodebuild clean -project Careerly/Careerly.xcodeproj -scheme Careerly -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.0'
  
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --force-exclude
        env:
          WORKING_DIRECTORY: Careerly